version: '3'

services:

  zuul-api-gateway-server:
    build: ./zuul-api-gateway-server
    ports:
      - 8765:8765
    environment:
      - zuul_routes_accommodations-service_url=http://accommodation-service:8080
      - zuul_routes_schedule-service_url=http://schedule-service:8080
      - zuul_routes_reservation-service_url=http://reservation-service:8080
      - zuul_routes_file-service_url=http://file-service:8080    

  findmyplace-config-server:
    build: ./findmyplace-config-server
    ports:
      - 8888:8888
    depends_on: 
      - rabbitmq
    environment:
      - SERVER_PORT=8888
      
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  swagger:
    image: swaggerapi/swagger-ui
    ports: 
      - 8080:8080

  findmyplace-website:
    build:
      context: ./findmyplace_website
    environment:
      - REACT_APP_IMAGE_SERVICE_URI=http://localhost:8765/file-service
      - REACT_APP_ACCOMMODATION_SERVICE_URI=http://localhost:8765/accommodations-service
    ports:
      - 3000:3000
    depends_on: 
      - zuul-api-gateway-server

  accommodation-service:
    build: 
      context: ./accommodation-service      
    # ports:
    #   - 8180:8080
   
  reservation-service:
    build: ./reservation-service
    # ports:
    #   - 8280:8080 
    environment:
        - SERVER_PORT=8080
        - spring_rabbitmq_host=rabbitmq
        - schedule_service_uri=schedule-service:8080
        - accommodation_service_uri=accommodation-service:8080
        - accommodation_resource_url=http://accommodation-service:8080/accommodations/
    depends_on: 
      - rabbitmq
  
  schedule-service:
    build: ./schedule-service
    # ports:
    #   - 8380:8080   
    environment:
      - SERVER_PORT=8080
      - spring_rabbitmq_host=rabbitmq
      - spring_cloud_config_uri=http://findmyplace-config-server:8888
      - accommodation_service_uri=accommodation-service:8080
      - accommodation_resource_url=http://accommodation-service:8080/accommodations/
    depends_on: 
      - rabbitmq
      - findmyplace-config-server
  
  file-service:
    build: ./file-service
    # ports:
    #   - 8480:8080
    environment:
      - SERVER_PORT=8080