version: '3'

services:

  findmyplace-config-server:
    build: ./findmyplace-config-server
    ports:
      - 8888:8888
    depends_on: 
      - rabbitmq
    environment:
      - SERVER_PORT=8888
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  swagger:
    image: swaggerapi/swagger-ui
    ports: 
      - 8080:8080

  findmyplace-website:
    build:
      context: ./findmyplace_website
    environment:
      - REACT_APP_IMAGE_SERVICE_URI=http://localhost:8480/
      - REACT_APP_ACCOMMODATION_SERVICE_URI=http://localhost:8180/
    ports:
      - 80:3000
    depends_on: 
      - accommodation-service
      - file-service

  accommodation-service:
    build: 
      context: ./accommodation-service      
    ports:
      - 8180:8080
   
  reservation-service:
    build: ./reservation-service
    ports:
      - 8280:8080 
    environment:
        - SERVER_PORT=8080
        - spring_rabbitmq_host=rabbitmq
        - schedule_service_uri=schedule-service:8080
        - accommodation_service_uri=accommodation-service:8080
        - accommodation_resource_url=http://accommodation-service:8080/accommodations/
    depends_on: 
      - rabbitmq
  
  schedule-service:
    build: ./schedule-service
    ports:
      - 8380:8080   
    environment:
      - SERVER_PORT=8080
      - spring_rabbitmq_host=rabbitmq
      - spring_cloud_config_uri=http://findmyplace-config-server:8888
      - accommodation_service_uri=accommodation-service:8080
      - accommodation_resource_url=http://accommodation-service:8080/accommodations/
    depends_on: 
      - rabbitmq
      - findmyplace-config-server
  
  file-service:
    build: ./file-service
    ports:
      - 8480:8080
    environment:
      - SERVER_PORT=8080